# Generated by Django 3.0.6 on 2020-06-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('E', 'Efetivado'), ('O', 'Orçamento'), ('C', 'Cancelado')], max_length=1)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField()),
                ('observacoes', models.CharField(max_length=300)),
            ],
        ),
    ]
