# Generated by Django 3.0.6 on 2020-06-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
