# Generated by Django 3.0.6 on 2020-06-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_auto_20200630_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='movimento',
            field=models.CharField(blank=True, choices=[('s', 'saida')], default='s', max_length=1),
        ),
    ]
