# Generated by Django 3.0.6 on 2020-06-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('pedido', '0005_pedido_movimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoSaida',
            fields=[
            ],
            options={
                'verbose_name': 'pedido saida',
                'verbose_name_plural': 'pedido saida',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pedido.pedido',),
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(to='produto.Produto'),
        ),
        migrations.CreateModel(
            name='PedidoItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('saldo', models.PositiveIntegerField(blank=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedido.Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
