# Generated by Django 3.0.6 on 2020-07-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('id',)},
        ),
    ]
