# Generated by Django 3.0.6 on 2020-07-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_cadastro', models.DateField(auto_created=True)),
                ('razao', models.CharField(max_length=100)),
                ('fantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=9)),
                ('insc_est', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('Beb', 'Bedidas'), ('Cer', 'Cervejas'), ('Ali', 'Alimentos'), ('Ute', 'Utensílios')], max_length=3)),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endereco.Endereco')),
            ],
        ),
    ]
