# Generated by Django 3.0.6 on 2020-07-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ('rua',)},
        ),
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
